//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntytiModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class SaleSet
    {
        public int Id { get; set; }
        public System.DateTime Date { get; set; }
        public int CustomerId { get; set; }
        public int ProductId { get; set; }
        public int Summ { get; set; }
        public int ManagerId { get; set; }
    
        public virtual CustomerSet CustomerSet { get; set; }
        public virtual ManagerSet ManagerSet { get; set; }
        public virtual ProductSet ProductSet { get; set; }
    }
}
