//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntytiModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class WorkResults
    {
        public int Id { get; set; }
        public System.DateTime Date { get; set; }
        public string Customer { get; set; }
        public string Product { get; set; }
        public int Summ { get; set; }
        public string ManagerId { get; set; }
    
        public virtual Manager Manager { get; set; }
    }
}
